name: Contract Tests - Scheduled

on:
  schedule:
    - cron: "*/60 * * * 1-5"

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar o ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      
      - name: Instalar gems
        run: bundler install
        
      - name: Instalar o cucumber
        run: gem install bundler cucumber
        
      - name: Executar smoke tests
        run: rake smoke

      - name: Slack notification - Success
        uses: rtCamp/action-slack-notify@v2
        if: ${{ success() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: test-report
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.clipartmax.com/png/middle/179-1795386_patient-success-success-icon-png.png
          SLACK_MESSAGE: ':alarm_clock: Testes Agendados executados com Sucesso! :white_check_mark:'
          SLACK_TITLE: ':alarm_clock: Testes Agendados executados com Sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO
        
      - name: Slack notification - Falha
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: test-report
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.vhv.rs/dpng/d/431-4316378_error-icon-hope-for-justice-logo-hd-png.png
          SLACK_MESSAGE: ':alarm_clock: Testes Agendados executados com Falhas! :fire:'
          SLACK_TITLE: ':alarm_clock: Testes Agendados executados com Falhas! :fire:'
          SLACK_USERNAME: FALHA
