name: Smoke Test

on:
  push:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar o ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      
      - name: Instalar gems
        run: bundler install
        
      - name: Instalar o cucumber
        run: gem install bundler cucumber

      - name: Executar smoke tests
        run: rake smoke
